name: Java Cucumber CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-report:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java JDK 1.8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '1.8'
          distribution: 'temurin'
          cache: maven  # Automatically caches ~/.m2/repository

      # Step 3: Build project and run tests
      - name: Build project and run tests
        run: mvn clean verify

      # Step 4: Generate Cucumber HTML report
      - name: Generate Cucumber HTML report
        run: mvn net.masterthought:cucumber-reporting:generate

      # Step 5: Upload HTML report as artifact
      - name: Upload HTML report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Cucumber-HTML-Report
          path: target/HTML-reports
