name: Java Cucumber CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '1.8'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build project and run tests
      run: mvn clean verify

    - name: Generate Cucumber HTML report
      run: mvn net.masterthought:cucumber-reporting:generate

    - name: Upload HTML report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: Cucumber-HTML-Report
        path: target/HTML-reports
